### ISSUE TITLE
drones would not fix the cable faults

### ISSUE THREAD

**Issue by igorpodobnik** [ChoGGi/SurvivingMars_CheatMods#1]
Hi, have used your set of mods and only used one, to have free maintenance of buildings. however now, the drones do not wish to fix any of the faulty cables meaning my power is just drained away...

Any way to counter that?

**Comment by igorpodobnik** [comment]
side note, when added the instant build pipes it seems it solved the breaking issues since pipes are now unbreakable and so are cables, lost two spaces for breakthroughts tho

**Comment by ChoGGi** [comment]
They break down when you have it enabled, or they were already broke down?

**Comment by aryanQ** [comment]
Hi, the arcology+ has a problem, the drones won't repair it. First it stated "kiene_wartung" as the name of the maintenance supply which automatically rendered it fixless. then I changed it to polymers in the lua file, the amount was already set to 4000 which means 4 polymers. Still the drones won't repair the damn thing.
What to do???

**Comment by ChoGGi** [comment]
I've found a way to stop maintenance from building, it'll be in the next update of CheatMenu.

**Comment by ChoGGi** [comment]
I added an option to instant repair all the pipes/cables, as well as changing the method for free maintenance
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/d94447c17af813e684b2a355f1e097fa56a0ab64

**Comment by ChoGGi** [comment]
Updated
