### ISSUE TITLE
Please add an option to toggle the building menu cheats!

### ISSUE THREAD

**Issue by camk16** [ChoGGi/SurvivingMars_CheatMods#10]
Would be great to see F2 also toggle this menu:

![untitled](https://user-images.githubusercontent.com/30790283/40330905-5a6b586a-5d03-11e8-9052-0daa1155d225.png)

..or add an additional hotkey for it? Ctrl+F2 would be perfect!

Thanks!

**Comment by ChoGGi** [comment]
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/f96b1bc9ca4c04b584146466b45e257c8ebe5804

**Comment by camk16** [comment]
@ChoGGi - Thank you very much, kind sir!

**Comment by ChoGGi** [comment]
This should remove your need to toggle them now :)
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/b5f2453c6b4ddbb499885ab993f2e86a425f4e47
