### ISSUE TITLE
Add Function To Disable History Show On Screen? + UI Warning Spam

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [ChoGGi/SurvivingMars_CheatMods#11]
Hi, since new ver of ECM and the new Curiosity Update I keep getting a screen full off "[UI Warning] Assigning Window id 'id' of XTextButton to XTextButton" when I click on any object that being still constructed, also CLS command only clears the screen of all history I don't see a way to stop ECM from recording any history on screen.

"CheatMenuModSettings" not needed as I deleted the settings file and issue still occurs and nothing in log shows "XTextButton"

[Image](https://i.imgur.com/T7WKWlF.jpg)

also ECM menu hangs around in main menu after leaving an active game.

I'll provide log & mod list if you cannot reproduce any of this.

**Comment by ChoGGi** [comment]
That msg is a present from the devs, grab guthub version to remove it

>I don't see a way to stop ECM from recording any history on screen.
Menu>Debug>Console Toggle History

>also ECM menu hangs around in main menu after leaving an active game.
Yeah, mods aren't removed when you go to the main menu.
