### ISSUE TITLE
Map Exploration Menu Missing?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [ChoGGi/SurvivingMars_CheatMods#12]
as of Commit: 9cb3a52a2443b6d119bd1606b24e61f352f8b376 I noticed the map Exploration Menu from Cheats has vanished,

last known commit to still have this is: 281508d65603ce9ab04dd513946e2c7caabca8af

& I cannot find this Menu in any part of ECM up to commit ef8a6a7682199cf0df08b4ba522cc75e9deb8d1f <-- Latest

I reset/delete config for ECM as always.

**Comment by ChoGGi** [comment]
Hmm, Could you start the game, open the "Cheats" menu then quit and post a log?

**Comment by XxUnkn0wnxX** [comment]
Log: https://gist.github.com/XxUnkn0wnxX/ee4a07a64bc84f2b28d505d8b8c6446e

**Comment by ChoGGi** [comment]
See if this fixes it
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/5bb52528a1fe439d678889af65f4d548bbff9cea

**Comment by XxUnkn0wnxX** [comment]
nope cheat menu tab still does not contain the Map exploration Menu
Log: https://gist.github.com/XxUnkn0wnxX/4fc5e75c0ea65d3cb0aef29b5d5d93cd

**Comment by ChoGGi** [comment]
No I reproduced the error, grab the latest commit

Best I can tell hpk archiver got confused about EOF?
changed the variable name to one with a different length and problem solved...
