### ISSUE TITLE
Unable to scan anomalies due to missing global name

### ISSUE THREAD

**Issue by mys721tx** [ChoGGi/SurvivingMars_CheatMods#16]
When Anomaly scanning is clicked, the function errors out: 
```
... attempted to call a nil value (global 'BuildNames')
```

The affected code is:

https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/5384af567de52c83e8b3f1a1e60954a973278dd6/Expanded%20Cheat%20Menu/Code/Menus/CheatsFunc.lua#L793

**Comment by ChoGGi** [comment]
Hmm, thanks no idea what that's there for, and it works fine without it, be fixed next update.
