### ISSUE TITLE
CleanAndFix Freezing Game

### ISSUE THREAD

**Issue by Vortox14** [ChoGGi/SurvivingMars_CheatMods#17]
![image](https://user-images.githubusercontent.com/12583772/57988918-56e46f00-7a59-11e9-87e1-dbbf1c136924.png)
Not sure if the screenshot helps.

[MarsSteam.exe-20190519-17.03.22-5cc1c744.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/3195672/MarsSteam.exe-20190519-17.03.22-5cc1c744.log)

Hitting ESC after using cheat command 'CleanAndFix', seems to avoid the issue. but if you click off the object instead, the game freezes.
Adding dust works, but not removing it through the command.
Can manually remove it through various other interfaces provided by ECM.

**Comment by ChoGGi** [comment]
This was fixed in v13.5

**Comment by ChoGGi** [comment]
When I can update mods on paradox then this problem will be fixed

https://forum.paradoxplaza.com/forum/index.php?threads/surviving-mars-bad-input.1178958/
