### ISSUE TITLE
Diner first upgrade is completely broken [Upgrade Slots: Visitors/Capacity]

### ISSUE THREAD

**Issue by Traehgniw** [ChoGGi/SurvivingMars_CheatMods#18]
It costs electronics, as if it were a Service Bots upgrade, and makes the UI look like it acts like a Service Bots upgrade, but then it still requires workers but can't hire them, meaning that you just spent resources to make your diner not work, and you HAVE to do this in at least one diner to gain access to the upgrades that actually work. When you have the Service Bots breakthrough researched, Diners and only Diners do not have an available Service Bots upgrade. 

I do not have Cheats Menu installed at all.

**Comment by ChoGGi** [comment]
If you have it, mind posting a log of when you upgraded it, or just your latest log?

**Comment by Traehgniw** [comment]
![image](https://user-images.githubusercontent.com/42482668/60411537-5bd43b00-9c21-11e9-8fb1-efce83015ffe.png)
[MarsPDX.exe-20190701-16.53.39-5ced3d29.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/3343994/MarsPDX.exe-20190701-16.53.39-5ced3d29.log)

**Comment by Traehgniw** [comment]
i closed and reopened the game and the issue got even worse :( it won't let me upgrade it more than once, as you can see from the screenshot

**Comment by ChoGGi** [comment]
Why do you have so many duped mods?

You have Diner: Upgrade Slots installed which will mess up service bots

**Comment by Traehgniw** [comment]
heck that explains it

**Comment by ChoGGi** [comment]
Also you probably shouldn't install my fix mods, unless you are experiencing the issue they fix.
