### ISSUE TITLE
Drones won't fix the Arcology* building, might also affect unlimited wonders mod!

### ISSUE THREAD

**Issue by aryanQ** [ChoGGi/SurvivingMars_CheatMods#2]
Hi, the arcology+ has a problem, the drones won't repair it. First it stated "kiene_wartung" as the name of the maintenance supply which automatically rendered it fixless. then I changed it to polymers in the lua file, the amount was already set to 4000 which means 4 polymers. Still the drones won't repair the damn thing.
What to do???

**Comment by ChoGGi** [comment]
All that the arcology+ does is add 8 more spots for people
What other mods do you have activated, and is there anything in the log?


Do you have Maintenance Free enabled?

**Comment by aryanQ** [comment]
Hi, no arcology+ provides 120 spots! and all the mods I am using are from the ones here
they are: 1) arcology+ 2) CheatMod_DefensiveTurret 3) CheatMod_UnlimitedWonders

And no, I don't want maintenance free... I just want to be able to have more colonists in one dome.
The problem is maybe with the name or sth... that extra "+", maybe the drones don't recognize that in their programming for repairing? 
As I said, normally in the lua file there is this "keine_wartung" thingy written as the required maintenance resource type which resulted in the drones not doing anything about it. I thought I have to change the name to a resource defined in the game, yet to no avail..

**Comment by ChoGGi** [comment]
Ah, you're using BoehserOnkel's mod, I re-uploaded it with the + changed to X

I also added the ability to add more living spaces to CheatMod_CheatMenu, you can stick as many you want (just gotta figure out a way to limit the height, or toggle it).

**Comment by aryanQ** [comment]
Hey, I checked, but for the maintenance which is kinda the main issue, you still left that "keine wartung". The whole problem started because the drones can't repair the building.... any thoughts?

**Comment by ChoGGi** [comment]
Oh nuts, missed that bit :)
try it again

**Comment by ChoGGi** [comment]
Did that fix it?

**Comment by ChoGGi** [comment]
I'm going to assume it's fixed.
