### ISSUE TITLE
Romanian names

### ISSUE THREAD

**Issue by hmlendea** [ChoGGi/SurvivingMars_CheatMods#20]
Hello,

I've just noticed your mod that adds new countries and name lists, and I can help you with custom names for Romania.

I've previously gathered a huge of romanian names (male, female, family), which I'm still maintaining.

You can find them on this repo: [hmlendea/universal-name-generator](https://github.com/hmlendea/universal-name-generator)

Direct links:
 - [Male](https://github.com/hmlendea/universal-name-generator/blob/master/Wordlists/ro-persons-males.txt)
 - [Female](https://github.com/hmlendea/universal-name-generator/blob/master/Wordlists/ro-persons-females.txt)
 - [Family](https://github.com/hmlendea/universal-name-generator/blob/master/Wordlists/ro-persons-surnames.txt)

Those are all real romanian names that I've gathered over a long time. They contain their original spelling with diacritics. They have been also carefully selected, and I've not added any names that are exceedingly rare, or just straight taken from foreign languages.
I'm not sure if the game supports diacritics or not, but it is very easy to remove them using any online tool or something.

**Comment by ChoGGi** [comment]
Thanks, I'll add them (SM works fine with utf8).

**Comment by hmlendea** [comment]
Thanks.

Nice, I wasn't sure. Other Paradox games I've played didn't support UTF8.

**Comment by ChoGGi** [comment]
Updated the mod on github, I'll be uploading mods to steam/paradox once I get around to updating all the mod options for evans.

**Comment by ChoGGi** [comment]
Updated on steam
