### ISSUE TITLE
Breakthrough list cheat.

### ISSUE THREAD

**Issue by Teddybomb** [ChoGGi/SurvivingMars_CheatMods#21]
hi,

do i need a dependency mod for the "game rules: breaktrhough" mod?

there's 2 in Paradox mod manager and neither work, altough the v4 version does show the option in the menu and the v7 doenst.

Vg

**Comment by ChoGGi** [comment]
Oh, not sure how two of them got uploaded. I made sure there's just the one (working version) now. I tested to make sure it works fine, if it still doesn't work after you updated than try a new game with a breakthrough, quit then post the log here.

**Comment by Teddybomb** [comment]
it's not working and i cant find my logs

should that be in the main folder?

**Comment by ChoGGi** [comment]
game profile folder is at https://steamcommunity.com/sharedfiles/filedetails/?id=1777493789

**Comment by Teddybomb** [comment]
... i got it in the epic store, i'll have a dig.

**Comment by ChoGGi** [comment]
the profiles are always in the same place, other than windows store.

**Comment by Teddybomb** [comment]
[MarsEpic.exe-20191017-15.01.54-5d9b179b.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/3741887/MarsEpic.exe-20191017-15.01.54-5d9b179b.log)

**Comment by ChoGGi** [comment]
Not sure if it'll interfere, but you've still got the old version installed:
[mod] Loaded mod def Game Rules Breakthroughs(id ChoGGi_GameRulesBreakthroughs, version 0.04-004) from AppData/PopsMods/GameRules-Breakthroughs/
[mod] Loaded mod def Game Rules Breakthroughs(id ChoGGi_GameRulesBreakthroughs, version 0.05-005) from AppData/PopsMods/GameRulesBreakthroughs/

Looking at the log, is this you starting a new game with a game rule than quitting? It's a pretty long log for just doing that.

**Comment by Teddybomb** [comment]
so i fired up my game this morning and it's working.

i think i had to restart it.
