### ISSUE TITLE
Disable Annoying Sounds mod: please add small space bar

### ISSUE THREAD

**Issue by Amplifiction** [ChoGGi/SurvivingMars_CheatMods#22]
So many small space bars in my current game, and they all have the same song on repeat.

Thank you! :)

**Comment by ChoGGi** [comment]
Those are in with the regular spacebar option, does it not work?

**Comment by Amplifiction** [comment]
I exited my game to main menu, installed your mod, reloaded the game and turned off only the space bar under mod options. It didn't work then. After restarting the game... I don't know :) All but one bar are now quiet. They all have an active work shift with workers.

Installed via Epic Games, version 250553. All season pass DLC enabled. 7 other installed mods, all by you.

**Comment by ChoGGi** [comment]
Yeah alright, I got another request to add as well. I'll stick them both on the list.

**Comment by Amplifiction** [comment]
Thank you. The one noisy bar is the only one in a medium dome. All other small bars are quiet and in basic domes. Hope that helps.

**Comment by ChoGGi** [comment]
No idea about that :) Could try turning it off/on or demo n rebuild?

**Comment by Amplifiction** [comment]
Hi! Haven't played for a while. Tried it today and that didn't help. I have built more domes and bars and the music still pops up now and then. Erratic but bearable :)

**Comment by ChoGGi** [comment]
weird, it should be all or nothing not sure what's up.

**Comment by Amplifiction** [comment]
The music get suppressed most of the time, which is enough for me to not want to blow my brains out :)

I have an unrelated request if I may: for some time I've been wanting to see the number of total jobs in any given dome, vacant or not. When you select a dome, you get the "Colonists X/Y" stat, Y being the total residential capacity of that dome. A similar stat for jobs would enable players to easily see how balanced a dome is. (The way I see it, any dome that doesn't house children or seniors ideally has 1 work slot for every residential slot.) Work slots in external buildings would be tricky as they can be shared by multiple domes, so I think a separate "external jobs X/Y" stat would be ideal. I have no idea if any of this is possible though :)

**Comment by ChoGGi** [comment]
Good enough then :)

The request is definitely possible (I've done a bunch of stuff like that for my infobar more info mod), but I've got no time for modding (I'm pretty much just doing some fixes here n there for borked mods and that's it).

**Comment by Amplifiction** [comment]
Ok, well thanks for the mods you made and the work that still goes into them!
