### ISSUE TITLE
Suggestion for Disable Mouse mod: Also disable/remove the unnecessary icons

### ISSUE THREAD

**Issue by notNSANE** [ChoGGi/SurvivingMars_CheatMods#23]
Basically removing/hiding these icons would be enough:

![7KCEPnm](https://user-images.githubusercontent.com/7162375/74302950-fad42000-4d36-11ea-9846-c1ebea2bb742.jpg)

What would make it perfect would be centering the 4 time status icons, and removing the background, since it largely has no functionality now. Mind that pressing the Y button (Build menu) still has a minor visual change regarding those icons.

If this is too complicated, maybe you can tell me where to look? I might take a look on how to make a mod like this.

**Comment by ChoGGi** [comment]
Erm shouldn't be too hard to do, I'll add it as an option to the mod.

**Comment by ChoGGi** [comment]
Added (as a default off) mod option to v0.3
