### ISSUE TITLE
Expanded cheat menu mod not available on XboxOne

### ISSUE THREAD

**Issue by vsvetoslavov** [ChoGGi/SurvivingMars_CheatMods#24]
I recently noticed HUGE slowdowns and uninstalling mods one by one it turned out that Epxanded cheat menu mod was the cause for these slowdowns - with the mod enabled it was impossible to even start a new game. So... I uninstalled it. Performance improved a lot, but I noticed that the mod is no longer available  in the Paradox Mod Manager Unfortunately there is no other way to install the mod.
So I have 2 questions:
- Could the reason for horrible performance really be the cheat mod?
- Is intentionally missing from the Paradox Mod Manager? And if not - will it return?
Best regards
Vasil Svetoslavov

**Comment by ChoGGi** [comment]
As far as I know it doesn't cause any performance issues, but I wasn't the one to remove it from paradox platform; that was the devs choice (and as far as I know it won't be returning?).

**Comment by vsvetoslavov** [comment]
Sorry for reviving this - is there a way to install on xbox one other than the built-in mod manager?

**Comment by ChoGGi** [comment]
Nope :)
