### ISSUE TITLE
[Trade Pad All Resources] Fuel Trade Does Not Produce Fuel

### ISSUE THREAD

**Issue by GalacticRuler** [ChoGGi/SurvivingMars_CheatMods#25]
[Surviving Mars.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/4395956/Surviving.Mars.zip)

I know it says to not use it, but I did, and noticed that while the rocket took the resources it was supposed to, it did not unload any of the fuel it was meant to for the trade.

also: waste rock does not show up in the menu

localstorage.lua + relevant .log included, though I could not locate a timestamp within the log that seems to indicate anything at all of relevance to the mod in question.

Mod list is....lengthy, and mostly fixes developed by you, and assorted buildings.

**Comment by GalacticRuler** [comment]
It also just occurred to me the rocket left, but has not despawned & removed itself from my bar, and is still holding that landing pad as in use.

**Comment by ChoGGi** [comment]
Yeah, the mod doesn't work...
