### ISSUE TITLE
Some achievements missing

### ISSUE THREAD

**Issue by 7s3** [ChoGGi/SurvivingMars_CheatMods#26]
The game added 20 additional achievements for a total of 70.
There are only 50 achievements that you can unlock with the mod enabled for Steam/Windows. Any chance to update it? I could not find anything to edit in the files myself.
Thanks!

Edit: Using most recent commit, e6ee3cd

**Comment by ChoGGi** [comment]
You mean in ECM? That list will only show achievements you haven't unlocked yet.

**Comment by ChoGGi** [comment]
You can see the full list by pasting this into the console
~AchievementPresets
To unlock from that list, click an item, in the window that opens press "Exec Code" and paste in:
AchievementUnlock(XPlayerActive, o.id)

**Comment by 7s3** [comment]
> You can see the full list by pasting this into the console
> ~AchievementPresets
> To unlock from that list, click an item, in the window that opens press "Exec Code" and paste in:
> AchievementUnlock(XPlayerActive, o.id)

Weird, even ~AchievementPresets is only showing 50 instead of 70 achievements.

**Comment by ChoGGi** [comment]
It shows 70 for me, did you disable any dlc in the steam client?

**Comment by 7s3** [comment]
No I haven't changed/disabled anything other than installing your Library and ECM

**Comment by ChoGGi** [comment]
Post your latest log?
https://steamcommunity.com/sharedfiles/filedetails/?id=1777493789

**Comment by 7s3** [comment]
`*** executable info
Timestamp:     	5d77a261
Date:          	Tue Sep 10 06:17:21 2019


*** hardware info
CPU           	Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
CPU count     	4
Phys. Memory   	16321 MBytes
Memory In Use  	32%
Disk Free      	106426 MBytes


*** OS info
OS:            	Windows 10
Version:       	10.0.18363 


*** Debug::Init()


Language: English
					 time 0:00:00:344

*** RenderDevice::Init: started...

					 time 0:00:00:500
*** Texture headers: 20909 loaded, 0 newer, 11 ms

					 time 0:00:00:516
*** graphics info
GPU                            	AMD Radeon R9 200 Series (Feature Level: 11.1 { SAD4ShaderInstructions: True, ExtendedDoublesShaderInstructions: True, })
API                            	d3d11
GPU Driver Version             	26.20.15002.61
GPU Driver Package Version     	26.20.15002.61
					 time 0:00:00:609
Platform: {
	desktop = true,
	developer = false,
	editor = true,
	goldmaster = true,
	pc = true,
	pops = true,
	windows_store = true,
}

					 time 0:00:01:047
	Enumming all 2 sound devices
		Found a sound device 'Headphones (High Definition Audio Device)' (ID: {0.0.0.00000000}.{ea4c78ba-57a6-486c-8a75-b2d615b9a0f3}), format: 0000fffe, channels: 2, sample rate: 48000, bits: 16, role: 0000000f
		Found a sound device 'Digital Audio (S/PDIF) (High Definition Audio Device)' (ID: {0.0.0.00000000}.{1c59f651-d589-4ed4-b13f-461843436636}), format: 0000fffe, channels: 2, sample rate: 48000, bits: 16, role: 00000000
*** Sound device 'Headphones (High Definition Audio Device)' (ID: {0.0.0.00000000}.{ea4c78ba-57a6-486c-8a75-b2d615b9a0f3}), format: 0000fffe, channels: 2, sample rate: 48000, bits: 16
						 time 0:00:01:063
Lua revision: 249143
Assets revision: 26200
					 time 0:00:01:156
DTM started in 1024 mb
						 time 0:13:12:484
[mod] Loading mod metadata...
[mod] Mods (appdata) AppData/Mods/ChoGGi's Library AppData/Mods/Expanded Cheat Menu
[mod] Loaded mod def ChoGGi's Library Test(id ChoGGi_Library, version 8.00-080) from AppData/Mods/ChoGGi's Library/
[mod] Loaded mod def Expanded Cheat Menu Test(id ChoGGi_CheatMenu, version 15.00-150) from AppData/Mods/Expanded Cheat Menu/
						 time 0:13:12:516
Account storage loaded successfully in 24 ms
						 time 0:13:13:547
POPS: Setting root path C:\Users\r2b3\AppData\Roaming\Surviving Mars
						 time 0:13:13:625
[RM] Prefab marker versions: {
	[0] = {
		count = 66,
		hash = -528956378,
		height_hash = -1698947081,
		mask_hash = 1091376297,
		type_hash = -1218620523,
	},
	{
		count = 1393,
		hash = -745736807,
		height_hash = 432382957,
		mask_hash = 1040406322,
		type_hash = -2074021696,
	},
	{
		count = 26,
		hash = -887593796,
		height_hash = -184284940,
		mask_hash = 1146460319,
		type_hash = 1786723332,
	},
	{
		count = 35,
		hash = -1327770564,
		height_hash = -1513955646,
		mask_hash = 1668846196,
		type_hash = 594247860,
	},
}
[RM] Blanc maps: {
	count = 41,
	hash = -2062416046,
}
						 time 0:13:13:656
VideoImpl::Init(Movies/Main Menu.ivf)
						 time 0:13:16:797
Changing map to "PreGame"
						 time 0:13:16:875
*** Reloading assets from folder BinAssets/

						 time 0:13:17:766
POPS: [CurlCallManager::update] FAIL '00000243AAFE8980' http status was none of 100, 200, 304: 401
POPS: [CAccountLogInXboxTicket] Received errorCode:'Failure'
POPS: [CAccountLogInXboxTicket] Server returned success code but JSON reply says failure. This might indicate subtle failure modes.
POPS: [CAccountLogInXboxTicket] Received errorMessage:'Unauthorized'
						 time 0:13:17:781
[POPS]Windows store autologin failed: not-authorized
[mod] Loading mod items...
						 time 0:13:19:453
Map changed to "PreGame" in 2645 ms.
						 time 0:13:33:531
Changing map to "BlankBig_01"
						 time 0:13:42:484
Buildable grid ready: 10/748 valid zones.
						 time 0:13:42:563
[RM] Default preset Polymers_VeryLow selected for Polymers
						 time 0:13:45:688
starting sector selected: I1
game_settings:
    save_game_id: +WENR2z1clqKCzZp
    sponsor: IMM
    profile: rocketscientist
    mystery: random
    mystery_random: MirrorSphereMystery
    coordinates: 2S50E
    landing_spot: 
    logo: MarsExpress
map_conditions:
    altitude: 2418
    temperature: -15
    cold_wave: 36
    dust_devils: 92
    dust_storm: 36
    meteors: 133
map_resources:
    concrete: 108
    metals: 73
    precious_metals: 73
    water: 36
						 time 0:13:46:453
Map changed to "BlankBig_01" in 12911 ms.
						 time 0:14:07:125
VideoImpl::Init(Movies/Hint/desktop/GameStartRocket.ivf)
						 time 0:14:15:156
Changing map to ""
						 time 0:14:16:063
Map changed to "" in 906 ms.
						 time 0:14:16:078
VideoImpl::Init(Movies/Main Menu.ivf)
						 time 0:14:50:156
[mod] Loading mod metadata...
						 time 0:14:52:391
[mod] Loading mod items...
Reloading lua files
						 time 0:14:53:469
Reloading done
[mod] Loading ChoGGi's Library Test(id ChoGGi_Library, version 8.00-080) items from AppData/Mods/ChoGGi's Library/
						 time 0:14:53:641
[mod] Loading Expanded Cheat Menu Test(id ChoGGi_CheatMenu, version 15.00-150) items from AppData/Mods/Expanded Cheat Menu/
						 time 0:14:53:672
VideoImpl::Init(Movies/Main Menu.ivf)
						 time 0:14:57:906
Changing map to "PreGame"
						 time 0:14:57:984
[mod] Loading mod items...
Reloading lua files
						 time 0:14:58:828
Reloading done
[mod] Loading ChoGGi's Library Test(id ChoGGi_Library, version 8.00-080) items from AppData/Mods/ChoGGi's Library/
						 time 0:14:58:984
[mod] Loading Expanded Cheat Menu Test(id ChoGGi_CheatMenu, version 15.00-150) items from AppData/Mods/Expanded Cheat Menu/
						 time 0:15:00:328
Map changed to "PreGame" in 2416 ms.
						 time 0:15:23:500
Changing map to "BlankBig_02"
						 time 0:15:23:609
[mod] Loading mod items...
Reloading lua files
						 time 0:15:24:484
Reloading done
[mod] Loading ChoGGi's Library Test(id ChoGGi_Library, version 8.00-080) items from AppData/Mods/ChoGGi's Library/
						 time 0:15:24:641
[mod] Loading Expanded Cheat Menu Test(id ChoGGi_CheatMenu, version 15.00-150) items from AppData/Mods/Expanded Cheat Menu/
						 time 0:15:33:469
Buildable grid ready: 15/904 valid zones.
						 time 0:15:33:547
[RM] Default preset Polymers_VeryLow selected for Polymers
						 time 0:15:36:188
starting sector selected: I1
						 time 0:15:36:203
game_settings:
    save_game_id: 2lp4ibwqtKAPEewh
    sponsor: IMM
    profile: rocketscientist
    mystery: random
    mystery_random: AIUprisingMystery
    coordinates: 1S117E
    landing_spot: 
    logo: MarsExpress
map_conditions:
    altitude: 1148
    temperature: -15
    cold_wave: 36
    dust_devils: 81
    dust_storm: 123
    meteors: 108
map_resources:
    concrete: 146
    metals: 146
    precious_metals: 146
    water: 146
						 time 0:15:36:859
Map changed to "BlankBig_02" in 13354 ms.
						 time 0:15:38:781
VideoImpl::Init(Movies/Hint/desktop/GameStartRocket.ivf)
						 time 0:15:53:313
Error from function "ThreadErrorHandler" =  thread: 00000243D0AF81E8 AppData/Mods/ChoGGi's Library/Code/CommonFunctions.lua:568: attempt to index a string value (local 'params') 
GetStack:
 	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D0AF81E8 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D0AF81E8 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D0AF81E8 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
[LUA ERROR] attempt to index a string value (local 'params')
C:\Users\r2b3\AppData\Roaming\Surviving Mars\Mods\ChoGGi's Library\Code\CommonFunctions.lua(568): upvalue MsgPopup
C:\Users\r2b3\AppData\Roaming\Surviving Mars\Mods\Expanded Cheat Menu\Code\Menus\CheatsFunc.lua(226):  <>
        --- end of stack
						 time 0:16:28:719
ChangeVideoMode request: 1920 x 1080 0 Hz, Borderless, vsync: off
					 time 0:16:28:734
Changed video mode to: 1920 x 1080 (Borderless) vsync: off
ChangeVideoMode end.
					 time 0:16:52:578
DTM started in 256 mb
						 time 0:22:55:828
Error from function "ThreadErrorHandler" =  thread: 00000243D32ED018 AppData/Mods/ChoGGi's Library/Code/CommonFunctions.lua:568: attempt to index a string value (local 'params') 
GetStack:
 	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D32ED018 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D32ED018 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
Error from function "error" =  thread: 00000243D32ED018 attempt to index a string value (local 'params') 
GetStack:
 	CommonLua/Core/cthreads.lua(77):  <>
	[C](-1):  <>
	        --- end of stack
						 time 0:22:55:844
[LUA ERROR] attempt to index a string value (local 'params')
C:\Users\r2b3\AppData\Roaming\Surviving Mars\Mods\ChoGGi's Library\Code\CommonFunctions.lua(568): upvalue MsgPopup
C:\Users\r2b3\AppData\Roaming\Surviving Mars\Mods\Expanded Cheat Menu\Code\Menus\CheatsFunc.lua(226):  <>
        --- end of stack
						 time 0:37:21:609
VideoImpl::Init(Movies/Hint/desktop/SuggestConcreteExtractor.ivf)
`

**Comment by ChoGGi** [comment]
There's no DLC installed:
Lua revision: 249143
Assets revision: 26200
					 time 0:00:01:156
DTM started in 1024 mb

It should look like this:
Lua revision: 249143
Assets revision: 26200
Steam AppID: 464920
DTM started in 2048 mb
DLC armstrong loaded, lua revision 249143, assets revision 26200
DLC contentpack1 loaded, lua revision 249143, assets revision 26200
DLC contentpack3 loaded, lua revision 249143, assets revision 26200
DLC dde loaded, lua revision 249143, assets revision 26200
DLC gagarin loaded, lua revision 249143, assets revision 26200
DLC marsvision loaded, lua revision 249143, assets revision 26200
DLC preorder loaded, lua revision 249143, assets revision 26200
DLC shepard loaded, lua revision 249143, assets revision 26200
Reloading lua files
Reloading done

**Comment by 7s3** [comment]
Ahh got it, thanks. Wasn't sure if I needed to fully install it first or if the necessary files for achievements were already built into the game.
