### ISSUE TITLE
[Console] Can’t exit out of the build menu for passages

### ISSUE THREAD

**Issue by unbeatable-101** [ChoGGi/SurvivingMars_CheatMods#27]
I have to quit the game

**Comment by ChoGGi** [comment]
What mods you do have enabled?

**Comment by unbeatable-101** [comment]
Let me check

**Comment by unbeatable-101** [comment]
Silva - Essential files
7.16MB
V.31
Silva - Orion Heavy Rocket
5.85MB
V.6
True Dome Network
1.68MB
V.3
Increased Dome Work Area (25 hexes)
0.51MB
V.1
Remove Console Dome Cap
0.03MB
V.2
Run Away
0MB
V.2
Omega Unlocks All Slowly 
0.02MB
V.4
LukeH's Outposts
1.62MB
V.4
LukeH's Base Additions
1.2MB
V.6
More Speed Controls
0.19MB
V.1
Faster Warehouse
0.3MB
V.1
Add Water Each Sol
0.02MB
V.3
Auto Scrap Capsules
0.02MB
V.2
Enhanced Landscaping
0.93MB
V.2
ChoGGi's Library (Console)
0.36MB
V.7
Mod Options Expanded
0.02MB
V.4
Stop Colonist Death Failure
0.11MB
V.4
Silva - Automated Extractors
12.03MB
V.6
Silva - Large Universal Depot
5.86MB
V.5
Silva - Fueled Reactor
15.78MB
V.5
Silva - Cosmos Project Event
25.86MB
V.8
Cheat Mod: Longer Passages
0.98MB
V.3
Stellaris Radio
98.38MB
V.3
Rain Lakes
3.42MB
V.2
RC Commands
1.22MB
V.4
SpaceY Logo (SpaceX Look-a-like)
0.87MB
V.1
Opportunity
1.44MB
V.13
(QoL) Triboelectric Scrubber defaults to max range
0.85MB
V.1
Silva - Martian Observatory & Cosmos Project (part.1)
10.86MB
V.6
Silva - GeoReactor
12.43MB
V.3
Pins Missing Some Status Icons
0.01MB
V.1
Childrens Life
0MB
V.2
Drone Load Balancing
0.41MB
V.1
(QoL) Service Bots activate all shifts
0.92MB
V.1
Fix Expedition RC Commander
0.04MB
V.1
Passages Use Empty Hexes
0.11MB
V.1
Cheat Mod: Long Tunnels
0.43MB
V.1
Prefab Safety
0.02MB
V.2
Drone Idle Recharge
0.04MB
V.3
Catacombes de Mars
0.08MB
V.3
Silva - Modular Apartment
9.33MB
V.7
Elevator A.I.
0.44MB
V.5
Make First Martianborn Celebrity
0.02MB
V.2
The Monolith
3.42MB
V.2

**Comment by ChoGGi** [comment]
I don't think Passages Use Empty Hexes plays nice with Cheat Mod: Long Tunnels?
but you do got a few mods, so I'm just guessing

**Comment by unbeatable-101** [comment]
Yeah, tomorrow I’ll go through and disable some, I’ll tell you what one it was.

**Comment by unbeatable-101** [comment]
I disabled everything but the passages use empty hex’s and it still did not work

**Comment by ChoGGi** [comment]
It works fine on PC, so it's probably a console issue? I don't have an xbox to test on, and I do do some funkyness to get it working.

**Comment by unbeatable-101** [comment]
Do you have a controller you could pair to your PC? I think it might just be a problem with the limited number of buttons available.

**Comment by ChoGGi** [comment]
That worked fine as well

**Comment by unbeatable-101** [comment]
Well, guess it won’t cannot be fixed, I’ll mess around and see if I can do anything.

**Comment by ChoGGi** [comment]
Good luck :)
