### ISSUE TITLE
Another item to check for in "Fix Rocket Stuck"

### ISSUE THREAD

**Issue by dzfischer** [ChoGGi/SurvivingMars_CheatMods#29]
- Fueled rocket waiting on pad, selected planetary project to investigate which only required an RC Commander
- I only had a Europe's replacement (Seeker), so couldn't load the required payload
- Attempted to cancel mission, rocket got stuck on "unloading cargo"

This is a somewhat heavily modded game (mostly yours though xD), though don't think there's anything that jumps out as strictly interacting with missions, but you'd know best. **Could entirely be a mod conflict of some kind...**

![image](https://user-images.githubusercontent.com/47398228/98510829-c93ea580-2231-11eb-8ba0-a22784a8b535.png)

[Savefile](https://gofile.io/d/nkrX8S)
Log: [MarsSteam.exe-20201108-23.07.37-5d766754.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/5508698/MarsSteam.exe-20201108-23.07.37-5d766754.log)
Renamed local storage because git doesn't like lua files: [LocalStorage - Copy.lua.txt](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/5508702/LocalStorage.-.Copy.lua.txt)

**Comment by ChoGGi** [comment]
I left it for a min or two and it reset back to a regular rocket.

**Comment by dzfischer** [comment]
Huh, interesting. I left it for two Sols to no change, and again after exiting game and relaunching for good measure- chalk it up to a mod conflict then.

**Comment by ChoGGi** [comment]
Yeah couldn't say what's up, I loaded the save looked around in the rocket and it suddenly swapped back to a regular rocket, reloaded and it did the same.
