### ISSUE TITLE
[Request] 2 requests for building menu

### ISSUE THREAD

**Issue by AndRo-Marian** [ChoGGi/SurvivingMars_CheatMods#30]
1. If possible to move the top title to bottom.
    + Somehow if you can make the menu vertical and put it from Top Right like (Icon Text).
2. If possible to add buildings info for not researched buildings.
   - Not really need but is something.

**Comment by ChoGGi** [comment]
1. If you mean the menu in ECM, that's not my menu. I just enabled it (and added a couple menu items). I'll take a look and see though.
2. What exactly do you mean? Like where you want it etc?

**Comment by AndRo-Marian** [comment]
1. No. The game build menu.
2. Like in the game build menu to show all buildings that are not visible normal (You need to unlock it from research first) and the information bout it (If the building is not researched, normal is say to "Double click to open the research on it".

**Comment by ChoGGi** [comment]
1. You want the build menu on the right-hand side in a vertical fashion?
2. You want the building info added below that text?

**Comment by AndRo-Marian** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/48178307/107785615-76efb200-6d55-11eb-85f1-a7d466a901c6.jpg)

**Comment by ChoGGi** [comment]
I'm probably not going to finish this (xtemplates take too much faffing about).
