### ISSUE TITLE
[Olympus Hotel] Missing dependency on 1001514

### ISSUE THREAD

**Issue by lavock** [ChoGGi/SurvivingMars_CheatMods#31]
Mod don't load on 1001514 (Epic store). Installing it said there is Missing Dependency.

**Comment by ChoGGi** [comment]
It needs my library mod, pretty sure it's supposed to say that in the mod manager?

**Comment by lavock** [comment]
Works with the lib mod. I dont see where it is said, but my observation skill may be lacking :/. Ty for your mods btw.

**Comment by ChoGGi** [comment]
When you click a mod it'll show on the right side, above the change log.
