### ISSUE TITLE
Infobar More Info v2.3 does no longer work with my setup

### ISSUE THREAD

**Issue by wolfmanx** [ChoGGi/SurvivingMars_CheatMods#32]
The recent new version 2.3 of the Surviving Mars Mod Infobar More Info no longer works on my setup

-   Ubuntu 18.04
-   Steam Proton Experimental (since the new Linux binary requires GLIBC\_2.29, which Ubuntu 18.04 does not support).

Although I don't think it has anything to do with my specific setup ... the [test report source files](http://sw-amt.ws/surviving-mars/infobar-more-info-report/_static/infobar-more-info-report.zip) are attached.

Due to size limitations on github, the [rendered HTML report](http://sw-amt.ws/surviving-mars/infobar-more-info-report/README-infobar-more-info.html) and the [example savegame](http://sw-amt.ws/surviving-mars/infobar-more-info-report/_static/info_more_info_example.savegame.sav) are not included.

Test Report for Version 2.3
---------------------------

I have tested the module v2.3 by itself (incl. library dependency):

-   The tooltip for **Life support** is unmodified.
-   The mod options specify, that the module is enabled.
-   A [simple savegame](http://sw-amt.ws/surviving-mars/infobar-more-info-report/_static/info_more_info_example.savegame.sav) is available.

Test Report for Version 2.2 (Manual Installation)
-------------------------------------------------

I have copied the previous Version 2.2 module manually into the Steam module folder. The result shows, that the module works as expected:

-   When loading the [savegame](http://sw-amt.ws/surviving-mars/infobar-more-info-report/_static/info_more_info_example.savegame.sav), I get a warning about an incompatible module.
-   The tooltip for **Life support** is modified as expected.
-   The mod options do not show *Enable Mod*.

[infobar-more-info-report.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6183978/infobar-more-info-report.zip)

**Comment by ChoGGi** [comment]
I fudged a line, I'm just fixing something else and I'll upload 2.4

**Comment by wolfmanx** [comment]
The fix works perfectly. Thanks for all your hard work by the way! I would not want to play *Surviving Mars* without your mods anymore!

BTW, I was curious, so I saw this [cosmetic typo](https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/f757e1574684cf725fb8d42d9f31d7ca1c86a9c7#r48580770).

**Comment by ChoGGi** [comment]
*Whistles*

Thank you :)
