### ISSUE TITLE
rocket disappear immediatly

### ISSUE THREAD

**Issue by Delmr** [ChoGGi/SurvivingMars_CheatMods#35]
So uh, when i want to launch a rocket from earth, i can choose resource, colon and cie, but after, nothing appens, and when i build a rocket on mars, after the little animations of the gate, the rocket disappear.
there is no crash with this pb.
[MarsGOG.exe-20210328-11.26.33-60478ca8.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6217100/MarsGOG.exe-20210328-11.26.33-60478ca8.log)

[LocalStorage.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6217101/LocalStorage.zip)

https://we.tl/t-LVXOPD2Oe1 for dl the save,
thx u again for ur job, is great !

**Comment by ChoGGi** [comment]
There's nothing in the log, but I can tell you that you've got a mod that hasn't been updated for Tito.
