### ISSUE TITLE
Unlock Breakthroughs Modf

### ISSUE THREAD

**Issue by BluePuppet60** [ChoGGi/SurvivingMars_CheatMods#36]
First let me say your wonderful!! 
I came across a problem with this mod. I turned off all my mods and turned them on one at a time after quitting each time to find the mod creating this problem. When I use this mod with Alien Imprints selected, building on raised surfaces does not work. Build items just drop thru to the flat surface. It is really strange. I can use your Breakthrough Game Rules Mod with Alien Imprints and do not have this problem. Just wanted you to be aware :) 
Have a great day, and keep up the modding <3

**Comment by ChoGGi** [comment]
Huh, that's odd since I'm just unlocking the bt like the game... I'll take a look see

**Comment by ChoGGi** [comment]
What is a raised surface? and how do I reproduce this?

**Comment by BluePuppet60** [comment]
I was using map 3s172e its the raised area to the west of the starting zone.

**Comment by BluePuppet60** [comment]
When I try to build on this area it just makes a hole in the ground as the object falls trough.

**Comment by ChoGGi** [comment]
oh, yep that happened :)

**Comment by BluePuppet60** [comment]
its really strange lol :)

**Comment by ChoGGi** [comment]
It "works" now (no clue why it does that)...

**Comment by BluePuppet60** [comment]
Thanks so much :)
