### ISSUE TITLE
expanded cheat menu xbox

### ISSUE THREAD

**Issue by rastlin13** [ChoGGi/SurvivingMars_CheatMods#37]
When i have expanded cheat menu enabled I can not have rockets.  this includes the starting rocket when starting a new game.  I can resupply and load a rocket but it wont actually send it.  i tested it with just ChoGGi library and construction show dust grid enabled. this is on xbox so i don't know how to send files.  I also tried it with all 63 mods i have and its the same result. with expanded cheat mod enabled no rockets disabled i have rockets.   also is there a setting I am missing in show dust grid because i cant seem to get it to show when building nearby a dust producer.

**Comment by ChoGGi** [comment]
ECM isn't on xbox anymore, so you've got a very old version that hasn't been updated since before Tito.

And possibly the same for show dust grid (it's on v2.1)

**Comment by rastlin13** [comment]
ok thanks sucks that some people have to report everything first.  thanks for all the other mods.

**Comment by ChoGGi** [comment]
Show dust grid should be working, assuming it's up to date and my lib mod is as well (v9.7).
