### ISSUE TITLE
Vegetation does not grow on flattened terrain soil

### ISSUE THREAD

**Issue by harshil21** [ChoGGi/SurvivingMars_CheatMods#38]
Not sure if this qualifies as a bug or not, but after I used the Flatten terrain option under Game>Terrain, the soil quality on the flattened terrain was not being affected by my Forestation Plant. This really sucks cause now my local soil quality isn't improving and I don't want to cheat that part in (also the grass/lichen doesn't grow). Is there any fix? Or maybe a way to revert this? Will have to go to a very old save otherwise :(

[MarsGOG.exe-20210430-03.48.59-6058b7e0.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6410313/MarsGOG.exe-20210430-03.48.59-6058b7e0.log)

**Comment by ChoGGi** [comment]
I wouldn't be too hopeful, I made that a long time before green planet

**Comment by harshil21** [comment]
Thanks for the quick reply! Just extracted and replaced the files downloaded from master. The issue seems to have been fixed in this new creative world, but the soil quality representation is not showing up (and the % in the infobar).

![image](https://user-images.githubusercontent.com/37377066/116796378-7a473e00-aaf9-11eb-8048-b8f71f62c7d6.png)

**Comment by harshil21** [comment]
Oh wait nvm, I was being stupid. It is fixed completely. Sorry for the confusion! Thank you!
![image](https://user-images.githubusercontent.com/37377066/116796513-a3b49980-aafa-11eb-94fe-cb539fff859b.png)

**Comment by ChoGGi** [comment]
Good to know :)
