### ISSUE TITLE
[Console] the CSA mod stops drones from appearing in the resupply screen

### ISSUE THREAD

**Issue by unbeatable-101** [ChoGGi/SurvivingMars_CheatMods#39]
CSA
![E0AB1895-E81B-466A-9BF8-68E9CABEBB35](https://user-images.githubusercontent.com/58151048/117596057-74141b80-b110-11eb-8e2f-4cd9cf9af65b.png)
International Mars Mission 
![57F5E937-F1C1-403B-9B40-724B2DBDC974](https://user-images.githubusercontent.com/58151048/117596060-78403900-b110-11eb-9b56-971e13aa2dfa.png)

**Comment by ChoGGi** [comment]
Should be good now.
