### ISSUE TITLE
waste rock still not being stored

### ISSUE THREAD

**Issue by DaveFenner** [ChoGGi/SurvivingMars_CheatMods#4]
Brand new game, no other mods, concrete extractors stop working because waste rock storage. drones clear the water extractors just fine.

**Comment by DaveFenner** [comment]
![image](https://user-images.githubusercontent.com/35405087/38146525-6665c9da-341c-11e8-8dd1-9c1fbf0772b2.png)

**Comment by DaveFenner** [comment]
you can tell the drones to take the waste rock but they wont do it on their own.

**Comment by ChoGGi** [comment]
Try it now
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/d94447c17af813e684b2a355f1e097fa56a0ab64

**Comment by DaveFenner** [comment]
![image](https://user-images.githubusercontent.com/35405087/38155786-9f658bd2-3447-11e8-84b9-1228cb7cb91f.png)
same save game, updated your cheat. same issue.

**Comment by ChoGGi** [comment]
Would you mind attaching the save?

**Comment by DaveFenner** [comment]
ya how would i go about doing that? just the .sav right? 

https://mega.nz/#!FnY30RRD!niSQdqiBqOV0JtLntCd-XSQsfloDOQx18p5dnn5bDzU

Had to upload to a different site, file size too large.

**Comment by ChoGGi** [comment]
k, let me take a look

**Comment by DaveFenner** [comment]
where is that located?

**Comment by ChoGGi** [comment]
Same folder as your save folder (AppData/Surviving Mars)

**Comment by DaveFenner** [comment]
[CheatMenuModSettings.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1864952/CheatMenuModSettings.zip)

**Comment by ChoGGi** [comment]
I sped it up and it I didn't see anything ignored, it may have taken a little bit, but you could spawn some more drones?

**Comment by DaveFenner** [comment]
interesting. The only concrete extractors I have are near the bottom of the map. I have a drone hub right beside it and they still ignore the extractor.

**Comment by DaveFenner** [comment]
![image](https://user-images.githubusercontent.com/35405087/38156676-cd395240-344d-11e8-8a06-f772d830e78d.png)
I'm using a mod to distribute drones every hour so that can't be the problem. Literally just took that screenshot with the newest version cheatmod on.

**Comment by ChoGGi** [comment]
OK that's weird, your savegame doesn't have those extractors, its just the concrete

**Comment by DaveFenner** [comment]
interesting. well you could prob place them and get the same issue maybe?

**Comment by ChoGGi** [comment]
I just did that, and yep :)

**Comment by DaveFenner** [comment]
perfect. glad we could replicate it.

**Comment by ChoGGi** [comment]
I figured out what causes it, but I haven't had any luck in reversing it.
New version up, so at least it won't happen anymore (wanted to make sure it stops happening then see about fixing it).

**Comment by DaveFenner** [comment]
Do we have any update on this? Love the storage mods.

**Comment by ChoGGi** [comment]
Haven't had any luck no, best I could do is a mod that increases the building template size, but it would only apply to newly built storage.

**Comment by ChoGGi** [comment]
Forgot to update here, but I've somewhat re-added this option, but you do you need to restart the game for them to take effect.

**Comment by ChoGGi** [comment]
I just stumbled across the fix ;)
Drones will refuse to carry if you set their carry amount above the building storage amount...
