### ISSUE TITLE
Incompatible Mod Version When Loading Old Save

### ISSUE THREAD

**Issue by crsiebler** [ChoGGi/SurvivingMars_CheatMods#40]
![image](https://user-images.githubusercontent.com/1928630/123179337-06148100-d43e-11eb-826a-4da38f555bdd.png)

**Comment by crsiebler** [comment]
Epic Games
Mod Version 24
Suggested Game Version 1001514
Windows 10

Using Paradox Mod Manager

**Comment by ChoGGi** [comment]
Fixed (might need to unsub/resub)
