### ISSUE TITLE
Game stuck when trying to build any dome

### ISSUE THREAD

**Issue by kcswalter** [ChoGGi/SurvivingMars_CheatMods#41]
Hello

I use the Steam version of the game, with mods installed (in steam version) from the Workshop.

In the last few days, I am completely unable to use the mods ChoGGi's library and Expanded Cheat Menu. Every single time I enable it, trying to select a dome (only a dome, whatever type) from the build menu freezes the game controls. The camera still pans, but nothing else works. I know it is the mod, because if I disable it and start a new game, it works. If then I save the game immediately, quit the game, restart, enable the mod, load the game, the freeze happens again. I moved this post from Steam to here as it seems the right place...

Unfortunately the log doesn't provide any information, as the only way to close the game is by forcing it...

I can provide a couple of savegame just before and after the mod was enabled, but github doesn't let me attach files that big...

The crash log (useless)
[MarsSteam.exe-20210718-19.23.04-6081a539.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6836677/MarsSteam.exe-20210718-19.23.04-6081a539.log)

A open and close log with all the available infos
[MarsSteam.exe-20210718-19.33.16-6081a539.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6836694/MarsSteam.exe-20210718-19.33.16-6081a539.log)

**Comment by ChoGGi** [comment]
Can you load a save then quit, that'll give me something in the log to look at, there's also an option in ECM to flush the log more frequently (console>settings>flush log*).

Your settings for ECM are stored in the same directory as your logs dir (look for LocalStorage.lua)

**Comment by kcswalter** [comment]
Yep, I forgot to add a decent log, so I edited... ;-)

Just in case, I'm adding the ECM settings.

I can't find the flush log setting anywhere, maybe I'm missing something...

[LocalStorage.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/6838090/LocalStorage.zip)

**Comment by ChoGGi** [comment]
![Clipboard Image](https://user-images.githubusercontent.com/1261282/126169964-1838914d-32ac-4775-8d71-d04fc0335e4b.jpg)

**Comment by ChoGGi** [comment]
Quit the game, open localstorage.lua and delete this line:
DefaultOutsideWorkplacesRadius = 25000,
