### ISSUE TITLE
Xbox Library Issue

### ISSUE THREAD

**Issue by DruidDakota** [ChoGGi/SurvivingMars_CheatMods#43]
Hey I’m an Xbox user wasn’t sure how to contact you but your Library has been disabled on the Paradox Mod Manager and I’m in the middle of my first big play through and am hoping it can be fixed or updated! I’m sure with the new releases and fixes from developers this is bound to happen, I just wanted to check in and confirm for myself and everyone else who loves your work that it will be useable in the future. Hope this is an ok forum to contact you and that I can hear back!

**Comment by ChoGGi** [comment]
No it hasn't, that was a copy uploaded by someone else (it didn't work).

My library is still available: https://mods.paradoxplaza.com/mods/7528/Any

**Comment by DruidDakota** [comment]
Thank you! I’m not quite sure what I did but it all worked out and everything running smoothly now!
