### ISSUE TITLE
About English.csv

### ISSUE THREAD

**Issue by aiawar** [ChoGGi/SurvivingMars_CheatMods#44]
Excuse me, where is the progress of Chinese version of English.csv? I think I can help. Can you send out the Chinese version of the document, so that I only need to make the rest of it Chinese?

**Comment by aiawar** [comment]
In fact, I have translated it once, and I am polishing it now.But what I want more is tell me how to make Chinese by myself, so that I can debug it myself.

**Comment by aiawar** [comment]
[English.csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7184915/English.csv)

**Comment by aiawar** [comment]
[Chinese(Simplified).csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7184921/Chinese.Simplified.csv)

**Comment by ChoGGi** [comment]
ChoGGi's Library\Locales\Schinese.csv

**Comment by aiawar** [comment]
> > Excuse me, where is the progress of Chinese version of English.csv? I think I can help. Can you send out the Chinese version of the document, so that I only need to make the rest of it Chinese?
> 
> You're the first person to translate any of my mods (congrats).
> 
> ChoGGi's Library\Locales\Schinese.csv
[Chinese (Simplified).csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7186200/Chinese.Simplified.csv)
I found that the previous version would appear garbled, so I re-edited it with Modern CSV software and corrected the error of (< green>%s</green >), which is new.

**Comment by ChoGGi** [comment]
Okay to use it in the next update?

**Comment by aiawar** [comment]
> Okay to use it in the next update?

If you want, of course.I will continue to polish it.
Because these 1,900 articles are just translated according to the sentences, there may be deviations in the game.  This problem can be left to be solved later. After all, the problem can only be found by applying it first.

**Comment by ChoGGi** [comment]
Thank you!

I'll probably update it Sun, so if you work on it before then, just send me an update here, or email@choggi.org, or ChoGGi#9210 (whatever works best for you)

**Comment by aiawar** [comment]
aiawar is a good one. I've been using it for a long time.

**Comment by ChoGGi** [comment]
Yea same here, mind if I ask about how long that took to translate? :)

**Comment by aiawar** [comment]
> 是的，这里也是，介意我问一下翻译需要多长时间吗？：)
I actually used it for two days, maybe more, and then I had to translate it into human language after machine translation. (Laughter)
Actually, I'm still revising it
[SChinese.csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7189086/SChinese.csv)
.

**Comment by ChoGGi** [comment]
Ah :)

**Comment by aiawar** [comment]
em……. Use the latest document today.
I want to wait until you update the MOD, so I'll take a break for now

**Comment by ChoGGi** [comment]
Thanks again!

**Comment by aiawar** [comment]
> Thanks again!

hey,I found a problem.Something is well but most of them are "missing text".
And, i find its doesnt need **""** in chinese,otherwise will happen "ECM"，"调试" ，etc…

**Comment by aiawar** [comment]
I am very depressed about this discovery, which means that I have done nothing in the past few days. In the morning, when I discovered this thing, I spent another day trying to fix it, but in the end, all I left was the memory of repeatedly switching from the game interface and CSV file and a bunch of "missing text".

**Comment by ChoGGi** [comment]
I fiddled around with it for a bit, but I'm not really sure why they don't get translated.

**Comment by aiawar** [comment]
> I fiddled around with it for a bit, but I'm not really sure why they don't get translated.

I know why,There are statements in the ID column that are not all numeric ids in the English.csv

**Comment by aiawar** [comment]
If you get rid of this problem, not only Chinese, but also your original English version will solve the problem of "missing text".
This problem should not have appeared. Although I noticed it at the beginning of translation, I thought it was a new rule. It seems that I was wrong. Haha _ (:3 ⌒) _.

**Comment by ChoGGi** [comment]
What do you want me to do?

**Comment by aiawar** [comment]
![20210920100131](https://user-images.githubusercontent.com/90889174/133951076-cfaa96b4-c141-4c95-9de4-136221bf6ee6.png)
![20210920100344](https://user-images.githubusercontent.com/90889174/133951098-62680f68-bf00-459d-b268-8b7c0129906b.png)
![20210920100428](https://user-images.githubusercontent.com/90889174/133951112-6985bc56-6efe-4dcb-b0b8-12b2d3fe6482.png)
Plz look at the picture. I deleted English from all ID columns, and Chinese appeared very well. So I hope you can process the English version again before I translate it.

**Comment by aiawar** [comment]
It's best to combine multiple columns in English into one column, and then put them into "text" in the three-column form of "id", "text" and "translation".

**Comment by aiawar** [comment]
![20210920101354](https://user-images.githubusercontent.com/90889174/133951425-ae6b3c03-9db4-4d09-ac86-bd63aed1aedd.png)
This kind of situation is usually unnecessary, and it is not conducive to the translation of the three-stage form.

**Comment by aiawar** [comment]
I can also feel the hardship of this process when translating, but I sincerely believe that if the original version is treated, it will be beneficial not only to the present but also to the future, please.

**Comment by aiawar** [comment]
![20210920102218](https://user-images.githubusercontent.com/90889174/133951741-dd68306c-1878-4679-885e-2c6d32253b8e.png)
I forgot, I can't find this part in the file, so I can't make it Chinese. How can I get it or please add it by the way?

**Comment by ChoGGi** [comment]
You mean the line breaks? That's how the game has it.
![lcalc](https://user-images.githubusercontent.com/1261282/133951782-b33cf46e-00a8-4b5e-abc2-66c3b822cb69.jpg)

**Comment by ChoGGi** [comment]
> 
> 
> ![20210920102218](https://user-images.githubusercontent.com/90889174/133951741-dd68306c-1878-4679-885e-2c6d32253b8e.png)
> I forgot, I can't find this part in the file, so I can't make it Chinese. How can I get it or please add it by the way?

Those aren't translated strings, the game uses the actual function names to label them.

**Comment by aiawar** [comment]
Well, that's what I expected, but I don't know what will happen, so I asked you to deal with this problem. You know better than I do the impact of these changes. If you think that it is not suitable for changes, you can keep them first, and then I will try to deal with them.

**Comment by aiawar** [comment]
> > 我忘了，我在文件里找不到这个部分，所以我不能把它变成中文。我怎样才能得到它，或者请把它加进去？
> 
> 这些不是翻译的字符串，游戏使用实际的函数名来标记它们。

ok,anyway, I have localized the introduction of these strings and can also see them.

**Comment by aiawar** [comment]
By the way, please forgive this strange tone, because my words are more converted by translation software.

**Comment by ChoGGi** [comment]
No worries, I kinda figured that.

> If you think that it is not suitable for changes, you can keep them first, and then I will try to deal with them.

I can't change the strings from being that way, or the game won't load them properly :(

**Comment by aiawar** [comment]
Include those statements in the ID column, too?

**Comment by aiawar** [comment]
Then I'll have to figure it out alone.

**Comment by ChoGGi** [comment]
> Include those statements in the ID column, too?

?

**Comment by aiawar** [comment]
I mean, can't you delete them or move them to another location？
![20210920100131 (2)_LI](https://user-images.githubusercontent.com/90889174/133954966-b7c8971c-e43a-4878-a06c-66089d315420.jpg)
?

**Comment by aiawar** [comment]
This is what I think is the ideal forma
![20210920114209](https://user-images.githubusercontent.com/90889174/133955107-bc7ff88a-c515-4694-b742-ccc1998677b9.png)
t.

**Comment by ChoGGi** [comment]
> 
> 
> This is what I think is the ideal forma
> ![20210920114209](https://user-images.githubusercontent.com/90889174/133955107-bc7ff88a-c515-4694-b742-ccc1998677b9.png)
> t.

Yeah, that is?

**Comment by aiawar** [comment]
The ID part is pure numbers, the text part is your English text, and the Translation part is my Chinese translation.

**Comment by aiawar** [comment]
In fact, I'm doing the same now, and it's effective.

**Comment by aiawar** [comment]
Except those problems that I told you about using text to occupy ID part and discontinuous text.

**Comment by aiawar** [comment]
So I simply deleted or merged it, but which parts were difficult for me to test.

**Comment by aiawar** [comment]
> 是啊，是吗？
[SChinese.csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7193865/SChinese.csv)
This version of the file is available, and more than 90% of the files have been perfectly localized.

**Comment by aiawar** [comment]
The disadvantage is that as I said before, a part of the text was deleted and changed into the format I said. You can experience it.

**Comment by aiawar** [comment]
There are too many posts in this issue, so I'm going to reopen a new issue

**Comment by ChoGGi** [comment]
> 
> 
> > 是啊，是吗？
> > [SChinese.csv](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/7193865/SChinese.csv)
> > This version of the file is available, and more than 90% of the files have been perfectly localized.

Looks good
