### ISSUE TITLE
Autonomous Drones - Drone Work Delay issue

### ISSUE THREAD

**Issue by Viratak** [ChoGGi/SurvivingMars_CheatMods#45]
Not really a big issue since we can solve it with the options given but wanted to report it

### Issue 

Having Drone Work Delay set to 1 or more can lead rockets to not fuel, empty or be able to launch.

This behavior seems to be caused by rockets still waiting for drones that have been packed to arrive.

**Additional notes :**

Fix Rocket Stuck does not work in this weird case where the drone does not really exists, and it can only work for rockets with ```takeoff in progress```(Solved only 1 of my 8 or 9 stuck rockets)

### Current Solutions

**Manual Unstuck :** by (in order) setting the ```drone_entering``` rocket's array length to 0 and removing the entry, then deleting the glitched entity. - Used this to solve rockets before fiddling 

**Set Drone Work Delay to 0 :** Prevent drones from getting packed if they are doing something - I've been trying this solution for the last 3 hours and no more rockets stuck so far (I'll come edit if it ever changes)

### Possible Implementations

**Turning Drone Work Delay OFF by default**: Would prevent people from having this issue from the start and does not prevent the mod from working well (IMO better drone behavior overall)

**Check the task the drone is doing** and don't pack it if it's related to entering a rocket

I'll check later if there is any specific drone property that make it glitched (Haven't really fiddled with the glitched drones yet other than deleting them)

**Comment by ChoGGi** [comment]
Thanks for taking the time to fiddle with it (I've been putting it off).

> Turning Drone Work Delay OFF by default
Better just to remove it altogether?

> Fix Rocket Stuck does not work in this weird case where the drone does not really exists, and it can only work for rockets with takeoff in progress(Solved only 1 of my 8 or 9 stuck rockets)
8 or 9? All from this mod?

**Comment by Viratak** [comment]
Actually I think the rocket solved by the fix rocket stuck mod was bugged because of the reposition rocket mod (I'm using it only 
 to move the first rocket landed to move it to a landing pad) I'll try some stuff with that later and if it's right I'll open another issue, but yes all the other rockets were stuck because of this mod, all waiting for a packed drone to arrive.

> Better just remove it altogether ?

I guess yes, unless someone find it useful to force move drones that are already working

**Comment by Viratak** [comment]
Confirming no more rocket stuck since I stopped using Drone Work Delay. (No rockets stuck over 10+ hours and a few test games, not even on moving them with the reposition rocket mod)
Closing the issue
