### ISSUE TITLE
The mods remove console dome cap and omega unlocks all are not compatible 

### ISSUE THREAD

**Issue by Bugman11** [ChoGGi/SurvivingMars_CheatMods#47]
I have tested both on thier own and they only cause a crash when they are enabled together.

Can't provide any logs or the sorts as I am on xbox but I can explain how it happened, I simply have the 2 mods active and then try to launch a new game, change nothing then start it up, it then crashes while loading.

**Comment by ChoGGi** [comment]
I enabled them both, loaded a save, and built an omega.

How do I reproduce?

**Comment by ChoGGi** [comment]
I enabled them both, started a new game, built an omega. No crashes.
