### ISSUE TITLE
Black screen on new game

### ISSUE THREAD

**Issue by khuffsmp** [ChoGGi/SurvivingMars_CheatMods#5]
Whenever I enable only your mod and try to start a new game the screen is black. Buttons are still there I can see the cursor change and hear the button sounds. I can do an easy start and get in game and everything seems to work fine. I've tried both the mod nexus download as well as downloading straight from here.

**Comment by ChoGGi** [comment]
Is this a new development, or from your first try using it?
Could try starting a new game again, then alt-f4 once you get the black screen, and send your latest log?

**Comment by khuffsmp** [comment]
Huh unable to replicate it now. I played a normal non-modded game for a while earlier and it crashed on me. Started it up to get the log, enabled the mod and it worked as expected. I'd blame my computer before anything else.

**Comment by ChoGGi** [comment]
I'd blame the game, it seems to have a mind of it's own at times :)

**Comment by khuffsmp** [comment]
So looks like I was actually activating the regular cheat menu mod. Tried using yours again and it had the same issue. Log attached. 
[MarsSteam.exe-20180418-21.47.46-5ac49410.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1926471/MarsSteam.exe-20180418-21.47.46-5ac49410.log)

**Comment by ChoGGi** [comment]
Hmm, well first I'd remove these folders (it shouldn't matter, but they aren't doing anything so)
AppData/Mods/DecompileLUA
AppData/Mods/Mods BoehserOnkel
AppData/Mods/Mods ChoGGi

I also see the original Cheats Menu in there, not sure if it's enabled or not, and it probably shouldn't matter

If you could open CheatMod_CheatMenu\ReplacedFunctions.lua and remove from [here](https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/master/CheatMod_CheatMenu/ReplacedFunctions.lua#L352) to [here](https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/master/CheatMod_CheatMenu/ReplacedFunctions.lua#L363)

**Comment by khuffsmp** [comment]
No dice. Original cheats menu and all other modes are disabled btw. 

[MarsSteam.exe-20180418-22.57.31-5ac49410.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1926584/MarsSteam.exe-20180418-22.57.31-5ac49410.log)

**Comment by ChoGGi** [comment]
Alright, instead of deleting it; replace it with this

```
  --was giving a nil error in log, I assume devs'll fix it one day (changed it to check if amount is a number...)
  ChoGGi.OrigFunc.RequiresMaintenance_AddDust = RequiresMaintenance.AddDust
  function RequiresMaintenance:AddDust(amount)
    --(dev check)
    if type(amount) == "number" or luadebugger and (luadebugger:Type(amount) == "Point" or luadebugger:Type(amount) == "Box") then
      if self:IsKindOf("Building") then
        amount = MulDivRound(amount, Consts.BuildingDustModifier, 100)
      end
      if self.accumulate_dust then
        self:AccumulateMaintenancePoints(amount)
      end
    end
  end
```

**Comment by khuffsmp** [comment]
No change with that either. 
[MarsSteam.exe-20180419-17.35.37-5ac49410.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1929965/MarsSteam.exe-20180419-17.35.37-5ac49410.log)

**Comment by ChoGGi** [comment]
Really wish I could reproduce this error.
Now that someone else can also produce it
https://www.nexusmods.com/survivingmars/mods/7?tab=bugs


I've done some rearranging, hopefully my mod doesn't mess with whatever is being messed with...
Let me know how it goes :)

**Comment by ChoGGi** [comment]
northsidedown is saying the black screen is fixed, same for you?
https://www.nexusmods.com/survivingmars/mods/7?tab=bugs
