### ISSUE TITLE
Meteoroid Deposits - No compatible extractors available to build on Mars

### ISSUE THREAD

**Issue by GreenGinkgo** [ChoGGi/SurvivingMars_CheatMods#51]
It seems that the extractor is not visible in the build menu. I've checked every build menu methodically, but cannot see a compatible building. From the screenshot, you can see that I also have the elevator, so I definitely have B&B installed. I've restarted came software but still don't see the option. Can provide a log file if needed

![Screenshot 2022-03-02 153247](https://user-images.githubusercontent.com/5168056/156444917-1b173d64-8163-46a2-95e0-94ce0ee5c9f6.jpg)

Thanks so much for your hard work!

**Comment by ChoGGi** [comment]
Did you research the tech for them?
