### ISSUE TITLE
crashing in "UpdateShapeHexes" since latest update

### ISSUE THREAD

**Issue by bhayden53** [ChoGGi/SurvivingMars_CheatMods#52]
Hello,

Since the latest update I'm getting crashes on saving and the log has a lot of tracebacks from Construction.lua. Do you think this is related to any of your mods (I have a number of the construction hex mods installed)?

Here is the crash log
https://drive.google.com/file/d/1Rk4soWAflWn0Wydd15fyzOZ64gEHJq_M/view?usp=sharing

**Comment by ChoGGi** [comment]
Latest game update?

**Comment by bhayden53** [comment]
yes

**Comment by ChoGGi** [comment]
It might be dome teleporter, I'll take a look...

**Comment by bhayden53** [comment]
I disabled all of the "construction" mods and was still getting the crash. I re-enabled them and disabled Dome Teleporters, and now the game errors on saving, but doesn't crash.

**Comment by ChoGGi** [comment]
I'm disabling DT for now; till I build up the motivation to rebuild it.

(that could take awhile, this was an annoying mod to make)

**Comment by bhayden53** [comment]
no problem, it was really useful when I was building separate live/work domes, but I'm not really min/maxxing the game to that level anymore (since there's not a huge reward for doing it anyway)
