### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by Prectatorium** [ChoGGi/SurvivingMars_CheatMods#53]
None of [this](https://github.com/ChoGGi/SurvivingMars_CheatMods/issues/6), sorry.

I've gone through most of the [docs](https://github.com/HaemimontGames/SurvivingMars) here, there was only so much I could pick up on.
Going to be honest, don't really like Lua in this context, everything just seems all over the place.

I'm having difficulty attempting to implement the most basic of things, like, add a shortcut to reveal the map, and your tutorial section doesn’t seem to be sufficiently dumb down. Looking at [Add Salvage Hotkey](https://github.com/ChoGGi/SurvivingMars_CheatMods/tree/master/Mods%20ChoGGi/Add%20Salvage%20Hotkey) and [CheatsFunc.lua](https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/master/Expanded%20Cheat%20Menu/Code/Menus/CheatsFunc.lua) only got me frustrated due to failure after failure in attempting to get it to work. I know I’m not alone on this matter, modding for Surviving Mars isn’t for your average Joe, youtube just doesn’t have content, and all documentation I’ve look at appears to be for individual who are, at worst, already experiences in modding for this game.

So, getting to the point, would you consider adding to your tutorial section some tutorials that don’t have such a steep learning curve?

Funny thing, I don’t even use your mods, I would however like to make my own, implementing some things that are in your mods.

One more thing, there doesn’t seem to be a PM feature in github anymore, so this seemed the only way to get across. If it’s vexing, just remove this “issue”, and I’ll show myself out.

Kind regards.

**Comment by ChoGGi** [comment]
The issue is fine as a means of communication (for me at least)

You'll want to see here next time for the lua code/docs (the HG one is out of date)
https://github.com/surviving-mars/SurvivingMars

As in most projects, I've been very lazy about docing anything :)
I do have example mods that might be of use? As for adding a hotkey take a look at my enable console mod, it's fairly minimal
https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/master/Mods%20ChoGGi/Enable%20Console/Code/Script.lua#L36

**Comment by Prectatorium** [comment]
First things first, I really appreciate you replying.

If https://github.com/surviving-mars/SurvivingMars/tree/master/Docs is what opens when one runs the mod editor, I've been through most of the Lua content, but I’m going to have another look.

This works, thx a mil. Some edits regarding “OnAction” were required.

```
function OnMsg.ClassesPostprocess()

	local CommonShortcuts = XTemplates.CommonShortcuts

	CommonShortcuts[#CommonShortcuts+1] = PlaceObj("XTemplateAction", {
		"ActionId", "Tweaks_MapExplorationScan",
		"ActionTranslate", false,
		"ActionShortcut", "Alt-S",
		"OnAction", function (self, host, source)
			CheatMapExplore("scanned")
		end,
		"replace_matching_id", true,
	})
	CommonShortcuts[#CommonShortcuts+1] = PlaceObj("XTemplateAction", {
		"ActionId", "Tweaks_MapExplorationDeepScan",
		"ActionTranslate", false,
		"ActionShortcut", "Alt-D",
		"OnAction", function (self, host, source)
			CheatMapExplore("deep scanned")
		end,
		"replace_matching_id", true,
	})
end
```

You have no idea how happy I was when I got an error in the console log. I might as well pick your brain on more detail regarding this code, and that would be for this shortcut to work exclusively within the context of the “map view”. Just a pointer in the right direction. Some pseudo code:

`if in mapview then…`

I also got akarnokd’s AutoScanMap to work slightly differently, a thx both you and him. Instead of getting sectors close to an object, just go about scanning the sector with the highest tower bonus. As you can see, and most lightly expect, tiny edit, all the code is still his, comments and all.

```
    if UICity.ExplorationQueue and #UICity.ExplorationQueue == 0 then

        local scanCandidates = { }

        -- g_MapSectors is a column [1..10] and row [1..10] matrix of sector information
        -- 1, 1 is J0; 1, 10 is J9

        for x = 1, const.SectorCount do
            for y = 1, const.SectorCount do
                local sector = UICity.MapSectors[x][y];
                if sector:CanBeScanned() then
                    -- full scanning is enabled
                    if mode == "all"
                            -- do scanning only if deep scanning is not available
                            or (mode == "normal" and g_Consts.DeepScanAvailable == 0)
                            -- do scanning only if deep scanning becomes available
                            or (mode == "deep" and g_Consts.DeepScanAvailable ~= 0) then
                        scanCandidates[#scanCandidates + 1] = sector
                    end
                end
            end
        end

        -- if there are sectors to scan
        if #scanCandidates ~= 0 then
            -- find the bonus one to existing units and buildings

            local bonussector = nil
            local bonusvalue = 0
                                -- find bonus candidate
            for k, sector in ipairs(scanCandidates) do

                -- sector bonus
                local bonus = sector:GetTowerBoost(UICity)

                -- if this is the first sector or it is closer than something else before
                if bonus > bonusvalue then
                    bonussector = sector
                    bonusvalue = bonus
                end
            end

            -- queue it up for exploration
            if not bonussector then
                -- pick a random sector from the candidates
                bonussector = scanCandidates[ AsyncRand (#scanCandidates)]
            end
            bonussector:QueueForExploration()
            -- prevent the scan animation from being deployed on the main map view
            if GetInGameInterfaceMode() ~= "overview" then
                bonussector:SetScanFx(false)
            end
            OverviewModeDialog:UpdateSectorRollover(bonussector)
        end

    end
```

Now I know one never has enough time for anything, we are all very busy with our own lives, but, I’m going to insist regarding considering adding to your tutorial section some tutorials that don’t have such a steep learning curve, you know, so simpletons such as I, are able to at least start with something, as you just proved with your reply.

Enough testimony, thank you very much.

**Comment by ChoGGi** [comment]
For those hotkeys, you'll want to check if it exists
```
if not table.find(CommonShortcuts, "ActionId", "Prectatorium_MapExplorationScan") then
	CommonShortcuts[#CommonShortcuts+1] = PlaceObj("XTemplateAction", {
		"ActionId", "Prectatorium_MapExplorationScan",
		-- snipped
end
```

“map view” I assume you mean the map overview mode (zoomed out)
```
if Dialogs.OverviewMapCurtains then
end
```


> I’m going to insist regarding considering adding to your tutorial section some tutorials that don’t have such a steep learning curve

I won't say no, but I made those for people already familiar with the code, looking to do specific stuff.

**Comment by Prectatorium** [comment]
> For those hotkeys, you'll want to check if it exists (loading a save / starting another new game will dupe it)
> “map view” I assume you mean the map overview mode (zoomed out)
```
	if not table.find(CommonShortcuts, "ActionId", "Prectatorium_MapExplorationScan") then
		CommonShortcuts[#CommonShortcuts+1] = PlaceObj("XTemplateAction", {
			"ActionId", "Prectatorium_MapExplorationScan",
			"ActionTranslate", false,
			"ActionShortcut", "Alt-S",
			"OnAction", function (self, host, source)
				if Dialogs.OverviewMapCurtains then
					CheatMapExplore("scanned")
				end
			end,
			"replace_matching_id", true,
		})
	end
```

Done, works flawlessly.

> I won't say no, but I made those for people already familiar with the code, looking to do specific stuff.

Fortunately, I just finished some 800 hours of Elden Ring, I had time to “Git Gud”, so I'm going to be spending some hours going though your code, maybe expect more “issues” from me 😊.

Once again, thx for all the help, definitely made the difference.

**Comment by ChoGGi** [comment]
:)

Don't forget to check out my example mods
