### ISSUE TITLE
[Request] Dealing with flaws mod

### ISSUE THREAD

**Issue by hlechner** [ChoGGi/SurvivingMars_CheatMods#56]
First of all, Thanks for all the job on Surviving Mars community with your excellent mods!

I would like to request it, if you not interested I would like to ask for some tips on how to do it and I can try it myself to see if I can make it works.

The idea is to deal with the flaws that is not cured by sanatorium (except Renegade and flaws caused by events) in a way it sounds like a vanilla implementation (not a cheat), so I was thinking in two mods:

---

**Mod 1: Add (Loner, Hypochondriac, Whiner) to be treated by the default Sanatorium.**
**Description**: Since it does not include **Idiot** flaw, it will be like vanilla implementation, since Idiot flaw should be dealt differently due to the way they created this flaw.

Based on your answer of an user on reddit [here](https://www.reddit.com/r/SurvivingMars/comments/zligm9/comment/j05lsiu/?utm_source=reddit&utm_medium=web2x&context=3) I created this code, and works:
**Code**:
```lua
local function StartupCode()
	table.iappend_unique(g_SanatoriumTraits, {"Introvert"}) -- Loner
	table.iappend_unique(g_SanatoriumTraits, {"Hypochondriac"})
	table.iappend_unique(g_SanatoriumTraits, {"Whiner"})
end

OnMsg.CityStart = StartupCode
OnMsg.LoadGame = StartupCode
```

The only small bug is that After number 9 it do not show the icons, but it does not affect the usability:
![image](https://user-images.githubusercontent.com/11244067/212969775-c987d198-10b5-49a8-b911-8378605de417.png)

---

**Mod 2: Create a sanatorium exclusively to treat Idiot Flaw**
**Description**: Idiot flaw should be treated separately due to the fact it was intended to be annoying and without a proper way to deal with that (except killing them or force they be unemployed), Having that in mind to not be sound like cheat, I think the best way is to create a Sanatorium exclusively for idiots (spire as well) but it is way more expensive to build, take more time to cure compared with vanilla Sanatorium and it does have less work slot (maybe just 2 per turn?)

Some **names ideas**:
```
Psychiatric Center
Psychiatric Hospital
Mental Hospital
Asylum
BugHouse
```

**Apparence**:
To make it easier to do, maybe just a regular Sanatorium with different color patterns?

I don't have code for that one

**Comment by ChoGGi** [comment]
Thanks :)

> The only small bug is that After number 9 it do not show the icons, but it does not affect the usability:
Yeah, the devs only added numbers up to 9 in the images. I did do an example mod for more numbers, I should probably make that an actual mod...

I'll probably do the other mod as a basic sanatorium with idiot cure then let you figure out the fiddly bits?

**Comment by hlechner** [comment]
> I'll probably do the other mod as a basic sanatorium with idiot cure then let you figure out the fiddly bits?

Sure, thanks! i'm new to the mod world but with time definitely I can figure out based on your other mods and examples.

**Comment by ChoGGi** [comment]
Sry for the long reply, my install kinda borked itself.
[Psychiatric Hospital.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/10484542/Psychiatric.Hospital.zip)

**Comment by hlechner** [comment]
> Sry for the long reply, my install kinda borked itself. [Psychiatric Hospital.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/10484542/Psychiatric.Hospital.zip)

Don't worry about time, i'm in no hurry.

I think it borked because of a missplace of `.` (probably due to a missclick) on line 41, after i changed that everything works.

Thanks for the link/explanation of the template and color change function, it will helps a lot, but you code most of it, so probably will be just small details that I need to catch.

A will play a bit with the code specially the color and see what looks best, whatever the result I reach I will ask your opinion on that.

The things I'm doing:
- I removed the upgrade2 by commenting it (it adds the renegade to be cured)
- I will try to find a way to hide the options to choose the traits, since it will be exclusive for idiots
- I will play with colors, I will show you the results of that (after find a final one I can create a new tga file for display_icon)

**Comment by ChoGGi** [comment]
[Psychiatric Hospital.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/10486751/Psychiatric.Hospital.zip)

**Comment by hlechner** [comment]
```
-- Remove traits menu (sadly this also means the progress area)
-- I could probably do some hokey on selection removal of just the buttons?
```
yea, sadly the progress area is very useful, maybe an option to avoid the removal would be change the `max_traits` to 1, my idea about hide it was not just because it was not needed but because there was just 2 option valid: (auto and Idiot) and three buttons, so it look like broken since its not possible to select all them.

But adding this line:
```
max_traits = 1,
```
to the `DefineClass`, just showing one button and the `Idiot` will be already selected.

What do you think about it? Maybe it's easier

**Comment by ChoGGi** [comment]
If it works for ya ;) (I whipped that update before bed, it's your mod)

**Comment by hlechner** [comment]
Do you if it's possible to get the tga file of display_icon?

I was trying to create the icon with the real image of the sanatorium with the new colors, but the original icon its a lot better, probably it was rendered outside of the game, since it do not look identical, so I tried to screenshot and edit the original icon, it looks better, but I don't know how can I get that file (to get a bigger size):
`UI/Icons/Buildings/sanatorium.tga`

**Comment by ChoGGi** [comment]
You can use [hpk](https://github.com/nickelc/hpk/releases) to extract the icons in ui.hpk

![sanatorium](https://user-images.githubusercontent.com/1261282/214475679-5d556116-6715-496e-8868-dfb9f9ba68c3.png)

**Comment by hlechner** [comment]
Thanks!

What I made:
- Sanatorium icon modified `PsychiatricHospital.png` (from the one you last provided)
- `max_traits = 1` used to keep the progress area
- Mod preview image created (modified: `Preview.png`)
- Colors changed using the 3 palette_color (`outside_dark`, `inside_accent_medical`, `wonder_base`)
- Building description changed (`Treats Idiots using slow but effective ways, combining medicine, psychology and some unorthodox practices.`)
- Mod description added (`Specialized building to treat Idiots`)(metadata.lua)

I didn't changed the LICENSE file, but maybe you would like to update your copyright to 2023.

Even though it was my request, feel free to change anything you like, sure will be others users that will use this mod as well, no credits or mention needed.

Here is the file:
[Psychiatric Hospital.finish.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/10497004/Psychiatric.Hospital.finish.zip)

**Comment by ChoGGi** [comment]
Oh yeah, new year :) thanks

I'll upload it if you want, but I figured you'd want to do it (case you want to update something in it later)?

**Comment by hlechner** [comment]
My idea was to you publish it since you made all the work anyway, I just did small detail and I don't care about receive any credits for this, also you do have this awesome work in keep all your mods available in this repo and on paradox/steam.

But if you prefer I can publish it myself, no problem at all.

**Comment by ChoGGi** [comment]
Eh, either or. The mod you posted is fine as is?

**Comment by hlechner** [comment]
to me, it is.

**Comment by ChoGGi** [comment]
https://steamcommunity.com/workshop/filedetails/?id=2923594393

**Comment by hlechner** [comment]
Hey, just to update you about the Mod1 (add 3 traits to cure on sanatorium):

Based on your last comments, I tried to avoid keep sending comments, so, less work on your side, I uploaded it on my side:
https://steamcommunity.com/workshop/filedetails/?id=2924506941
https://mods.paradoxplaza.com/mods/56977/Any

I used the code I mentioned here and your example code for adding the icons, the License and your copyright is respected and kept on LICENSE file, also credit on description of the mod.

I will later create a github repo in the same style you do here and publish it there.

Thanks

**Comment by ChoGGi** [comment]
> Based on your last comments, I tried to avoid keep sending comments

I don't mind?
