### ISSUE TITLE
"Omega Unlocks All Slowly" inverted chance

### ISSUE THREAD

**Issue by sylar8376** [ChoGGi/SurvivingMars_CheatMods#58]
I'm flattered with credit in changelog but '>=' in 'AsyncRand(100)+1 >= mod_RandomChance' inverted the issue: it's now [50-100] (for 'AsyncRand(100)+1') to be true and [1-49] to be false, which is 49% to give breakthrough and 51% to fail (was 51%:49%).
Either 'AsyncRand(100)+1 > mod_RandomChance' or 'AsyncRand(100) >= mod_RandomChance' would give 50:50 chance though.

**Comment by ChoGGi** [comment]
:)
