### ISSUE TITLE
ChoGGi's Library - disabled due to content restrictions

### ISSUE THREAD

**Issue by kretze** [ChoGGi/SurvivingMars_CheatMods#61]
Steam Version
Mod: ChoGGi's Library (Mod Version 51)
Message: disabled due to content restrictions, today is July 28th. occurred for the first time

**Comment by ChoGGi** [comment]
https://www.reddit.com/r/SurvivingMars/comments/n2klhv/choggis_library_disabled_by_content_restrictions/

It'll be back up whenever someone is back in the office.
