### ISSUE TITLE
Funding Dialogue Does Not Open… CTD?

### ISSUE THREAD

**Issue by WillItWork** [ChoGGi/SurvivingMars_CheatMods#62]
Hello ChoGGi:

When I click on the funding command, nothing visible seems to happen.

1. Press F2 to reveal menu
2. Click ECM
3. Click Resources
4. Click Funding
5. ??

Later in the game, it crashed to desktop, which looking at the log, may not be related.

[MarsGOG.exe-20240805-21.04.40-627935d6.log](https://github.com/user-attachments/files/16529131/MarsGOG.exe-20240805-21.04.40-627935d6.log)
[LocalStorage.lua.NOT_ACTUALLY_A.txt](https://github.com/user-attachments/files/16529250/LocalStorage.lua.NOT_ACTUALLY_A.txt)

**Comment by ChoGGi** [comment]
That's already been updated/fixed, no idea about the ctd.
