### ISSUE TITLE
MapData Breakthroughs GP.csv, Column Latitude, all S'

### ISSUE THREAD

**Issue by CasuallyCorporate** [ChoGGi/SurvivingMars_CheatMods#63]
The csv at https://github.com/ChoGGi/SurvivingMars_CheatMods/blob/master/Map%20Locations/MapData%20Breakthroughs%20GP.csv 
seems to have all S' in the Latitude column.

I've replaced it with the column from one of the other csv's locally as they seem to generate the same. But thought you should know.

Kind regards,
CC

**Comment by ChoGGi** [comment]
Huh....

Thanks

#f3c6032
