### ISSUE TITLE
Elevator teaks : missing prefab

### ISSUE THREAD

**Issue by Elnhomantia** [ChoGGi/SurvivingMars_CheatMods#66]
I got an event (undergound) that gave me 3 underground dome. I got the prefabs, but not underground. Can't take the prefab from the surface to the underground even with your mod.
Could you add the prefab to the list please ? 

![image](https://github.com/user-attachments/assets/415363ee-6a0d-48c2-bce5-2a4c6453aada)

**Comment by Elnhomantia** [comment]
Nope sorry

**Comment by Elnhomantia** [comment]
Sorry again, the event name is : Mona Lisa
![image](https://github.com/user-attachments/assets/2300fc74-f72f-4630-ba2e-8d4df6e2ace8)
(it's the wiki)

**Comment by ChoGGi** [comment]
Oh, I already added a fix for that to my Fix Bugs mods.

**Comment by Elnhomantia** [comment]
which one ?

**Comment by ChoGGi** [comment]
Because it's a bug?

It's normally [here](https://mods.paradoxplaza.com/mods/36299/Any), but it got blocked (happens pretty regular for random mods), it'll be back up whenever paradox gets around to restoring it.
