### ISSUE TITLE
Game Freeze 'Expanded CM' tab

### ISSUE THREAD

**Issue by SadisticLlama** [ChoGGi/SurvivingMars_CheatMods#7]
Hi, 

I have no idea what happen, but every time I open the Expanded CM tab, my game freezes. The music keeps playing but nothing else happens, like it gets stuck in a loop or something. It doesn't happen with any other tab, just that one. It's not savegame specific, just whenever I open the tab.

It doesn't consume rediculous amounts of computer resources at or past the time of freeze either, though they do keep fluctuating, so I do think something happens in the background. 

It never unfreezes.

Gameversion: 229.422 (credits screen)

latest log: 
[MarsSteam.exe-20180429-10.55.29-5ada0a04.log](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1958573/MarsSteam.exe-20180429-10.55.29-5ada0a04.log)

CheatMenuModSettings (zipped cause github doesn't support .lua extensions?):
[CheatMenuModSettings.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1958574/CheatMenuModSettings.zip)

My (steamworkshop) mods enabled are:
- Advanced Air Tank v1.1
- AutoExplore
- Large Universal Depot v1.1
- Advanced Resources Depot v1.2
- More (Endless) Resource Buildings
- More Dome Buildings
- Increased Dome Work Area (25 Hexes)
- AutoGatherTransport
- Warp Speed (x5/x10)
- Mod Config

And this one in its mod folder in the appdata folder.

**Comment by ChoGGi** [comment]
Replace your CheatMod_CheatMenu\Settings.lua with the updated one.
