### ISSUE TITLE
OtherDepo not having any capacity and claims "not in reach of a drone commander"

### ISSUE THREAD

**Issue by Pernicio** [ChoGGi/SurvivingMars_CheatMods#8]
I'm using the latest version on GitHub, propably the 3.5 version.

At first the bug that made only 30 pieces of any material on all the depots that store a specific resource happened. Then I updated the mod with the files on GitHub, but for some reason, that didn't help either. Sometimes the bug where it only stores 30 occurs still, and sometimes it can't store anything. Disabling this mod fixes that.

The only mod I'm using along side this one is the Info Bar mod from Steam Workshop 
[Surviving Mars Mod Debug.zip](https://github.com/ChoGGi/SurvivingMars_CheatMods/files/1964966/Surviving.Mars.Mod.Debug.zip)

**Comment by ChoGGi** [comment]
>At first the bug that made only 30 pieces of any material on all the depots that store a specific resource happened.
I haven't heard of that happening before, the depots don't store above 30 each?

Could you upload the save game?

**Comment by Pernicio** [comment]
Ok, it happened again, when I enabled the "double amount of Breakthrough anomalies per game" option.

**Comment by Pernicio** [comment]
It seems to happen when ever I build a new deposit and try to choose the default 180, 250 works fine curently, allowing the maximum of 250 to be stored. Universal deposit works as intended with it's default settings.

**Comment by ChoGGi** [comment]
I'm sorry, but could you walk me through the exact steps you take to cause the issue?

**Comment by Pernicio** [comment]
Sure - I started the game, enabled all the commander bonuses and sponsor bonuses, enabled the "double amount of breakthrough anomalies per game" option. Then build a metal deposit, which showed it only could store 30 metals.

Now it temporarily fixed it self, but then again only allowed 30 metals to be stored, when ever I pressed the "default 180) or inputted it manually. Yet while this problem lasted some time, I tried all the setting, if they worked as intended, from 50 to 20 000 capacity and all the premade settings worked as intended.

Now when I tried to set it again to 180 after trying the premade settings, it worked this time again, allowing me to set and deposit the default 180 amount of metal to the depo. It is like this happens only sometimes and for reasons unknown to me gets fixed by it self when fidling with the premade capacity settings of the "Storage Other Depot". Also, custom amounts doesn't seem to work.

**Comment by ChoGGi** [comment]
https://github.com/ChoGGi/SurvivingMars_CheatMods/commit/1d0824fd2198a8e7af6872e2963560cf6e3cf0e9
Should be fixed now

**Comment by ChoGGi** [comment]
?

**Comment by Pernicio** [comment]
Sorry that it took a while, had to get some sleep :) But yes, it woprks correctly now! Thank you for the quick fix.

**Comment by ChoGGi** [comment]
Oh no worries, your other replies were quicker so :)
